version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver
      "
    restart: always
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
    command: celery -A test_develops_today worker --loglevel=WARNING
    restart: always
    environment:
      - DB_HOST=db
    volumes:
      - ./test_develops_today:/app
    depends_on:
      - db
      - redis
      - server
    profiles:
      - celery

  cron:
    build:
      context: .
    command: celery -A test_develops_today beat --loglevel=WARNING --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - server
    profiles:
      - celery

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/server/static
    ports:
      - "80:80"
    depends_on:
      - server
    profiles:
      - nginx

  redis:
    image: redis:alpine
    restart: always

volumes:
  db: