# Generated by Django 3.2.12 on 2022-03-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0002_auto_20220307_2111"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_name",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="update_date",
        ),
    ]
